/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedDatosMaestrosRouteImport } from './routes/_authenticated/datos-maestros'
import { Route as AuthenticatedDatosMaestrosIndexRouteImport } from './routes/_authenticated/datos-maestros.index'
import { Route as AuthenticatedDigitalAgentesRouteImport } from './routes/_authenticated/digital.agentes'
import { Route as AuthenticatedDigitalAppsRouteImport } from './routes/_authenticated/digital.apps'
import { Route as AuthenticatedDigitalInicioRouteImport } from './routes/_authenticated/digital.inicio'
import { Route as AuthenticatedHubInicioRouteImport } from './routes/_authenticated/hub.inicio'
import { Route as AuthenticatedHubModulosRouteImport } from './routes/_authenticated/hub.modulos'
import { Route as AuthenticatedHubProyectosRouteImport } from './routes/_authenticated/hub.proyectos'
import { Route as AuthenticatedDatosMaestrosAccesosEquipoCatalogosRouteImport } from './routes/_authenticated/datos-maestros.accesos-equipo.catalogos'
import { Route as AuthenticatedDatosMaestrosAccesosEquipoPersonalExternoRouteImport } from './routes/_authenticated/datos-maestros.accesos-equipo.personal-externo'
import { Route as AuthenticatedDatosMaestrosAccesosEquipoPersonalPropioRouteImport } from './routes/_authenticated/datos-maestros.accesos-equipo.personal-propio'
import { Route as AuthenticatedDatosMaestrosAccesosEquipoUsuariosRouteImport } from './routes/_authenticated/datos-maestros.accesos-equipo.usuarios'
import { Route as AuthenticatedDatosMaestrosEntidadesObraDireccionFacultativaRouteImport } from './routes/_authenticated/datos-maestros.entidades-obra.direccion-facultativa'
import { Route as AuthenticatedDigitalAppsIndexRouteImport } from './routes/_authenticated/digital.apps.index'
import { Route as AuthenticatedProyectoIdInicioRouteImport } from './routes/_authenticated/proyecto.$id.inicio'
import { Route as AuthenticatedProyectoIdModulosRouteImport } from './routes/_authenticated/proyecto.$id.modulos'
import { Route as AuthenticatedDatosMaestrosEntidadesObraPropiedadIndexRouteImport } from './routes/_authenticated/datos-maestros.entidades-obra.propiedad.index'
import { Route as AuthenticatedDatosMaestrosEntidadesObraPropiedadIdRouteImport } from './routes/_authenticated/datos-maestros.entidades-obra.propiedad.$id'
import { Route as AuthenticatedDatosMaestrosEntidadesObraProyectosIndexRouteImport } from './routes/_authenticated/datos-maestros.entidades-obra.proyectos.index'
import { Route as AuthenticatedDatosMaestrosEntidadesObraProyectosIdRouteImport } from './routes/_authenticated/datos-maestros.entidades-obra.proyectos.$id'
import { Route as AuthenticatedDigitalAppsActasReunionIndexRouteImport } from './routes/_authenticated/digital.apps.actas-reunion.index'
import { Route as AuthenticatedDigitalAppsActasReunionNewRouteImport } from './routes/_authenticated/digital.apps.actas-reunion.new'
import { Route as AuthenticatedDigitalAppsActasReunionIdIndexRouteImport } from './routes/_authenticated/digital.apps.actas-reunion.$id.index'
import { Route as AuthenticatedDigitalAppsActasReunionIdEditRouteImport } from './routes/_authenticated/digital.apps.actas-reunion.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatosMaestrosRoute =
  AuthenticatedDatosMaestrosRouteImport.update({
    id: '/datos-maestros',
    path: '/datos-maestros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatosMaestrosIndexRoute =
  AuthenticatedDatosMaestrosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDatosMaestrosRoute,
  } as any)
const AuthenticatedDigitalAgentesRoute =
  AuthenticatedDigitalAgentesRouteImport.update({
    id: '/digital/agentes',
    path: '/digital/agentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDigitalAppsRoute =
  AuthenticatedDigitalAppsRouteImport.update({
    id: '/digital/apps',
    path: '/digital/apps',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDigitalInicioRoute =
  AuthenticatedDigitalInicioRouteImport.update({
    id: '/digital/inicio',
    path: '/digital/inicio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHubInicioRoute = AuthenticatedHubInicioRouteImport.update({
  id: '/hub/inicio',
  path: '/hub/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHubModulosRoute = AuthenticatedHubModulosRouteImport.update({
  id: '/hub/modulos',
  path: '/hub/modulos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHubProyectosRoute =
  AuthenticatedHubProyectosRouteImport.update({
    id: '/hub/proyectos',
    path: '/hub/proyectos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatosMaestrosAccesosEquipoCatalogosRoute =
  AuthenticatedDatosMaestrosAccesosEquipoCatalogosRouteImport.update({
    id: '/accesos-equipo/catalogos',
    path: '/accesos-equipo/catalogos',
    getParentRoute: () => AuthenticatedDatosMaestrosRoute,
  } as any)
const AuthenticatedDatosMaestrosAccesosEquipoPersonalExternoRoute =
  AuthenticatedDatosMaestrosAccesosEquipoPersonalExternoRouteImport.update({
    id: '/accesos-equipo/personal-externo',
    path: '/accesos-equipo/personal-externo',
    getParentRoute: () => AuthenticatedDatosMaestrosRoute,
  } as any)
const AuthenticatedDatosMaestrosAccesosEquipoPersonalPropioRoute =
  AuthenticatedDatosMaestrosAccesosEquipoPersonalPropioRouteImport.update({
    id: '/accesos-equipo/personal-propio',
    path: '/accesos-equipo/personal-propio',
    getParentRoute: () => AuthenticatedDatosMaestrosRoute,
  } as any)
const AuthenticatedDatosMaestrosAccesosEquipoUsuariosRoute =
  AuthenticatedDatosMaestrosAccesosEquipoUsuariosRouteImport.update({
    id: '/accesos-equipo/usuarios',
    path: '/accesos-equipo/usuarios',
    getParentRoute: () => AuthenticatedDatosMaestrosRoute,
  } as any)
const AuthenticatedDatosMaestrosEntidadesObraDireccionFacultativaRoute =
  AuthenticatedDatosMaestrosEntidadesObraDireccionFacultativaRouteImport.update(
    {
      id: '/entidades-obra/direccion-facultativa',
      path: '/entidades-obra/direccion-facultativa',
      getParentRoute: () => AuthenticatedDatosMaestrosRoute,
    } as any,
  )
const AuthenticatedDigitalAppsIndexRoute =
  AuthenticatedDigitalAppsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDigitalAppsRoute,
  } as any)
const AuthenticatedProyectoIdInicioRoute =
  AuthenticatedProyectoIdInicioRouteImport.update({
    id: '/proyecto/$id/inicio',
    path: '/proyecto/$id/inicio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProyectoIdModulosRoute =
  AuthenticatedProyectoIdModulosRouteImport.update({
    id: '/proyecto/$id/modulos',
    path: '/proyecto/$id/modulos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatosMaestrosEntidadesObraPropiedadIndexRoute =
  AuthenticatedDatosMaestrosEntidadesObraPropiedadIndexRouteImport.update({
    id: '/entidades-obra/propiedad/',
    path: '/entidades-obra/propiedad/',
    getParentRoute: () => AuthenticatedDatosMaestrosRoute,
  } as any)
const AuthenticatedDatosMaestrosEntidadesObraPropiedadIdRoute =
  AuthenticatedDatosMaestrosEntidadesObraPropiedadIdRouteImport.update({
    id: '/entidades-obra/propiedad/$id',
    path: '/entidades-obra/propiedad/$id',
    getParentRoute: () => AuthenticatedDatosMaestrosRoute,
  } as any)
const AuthenticatedDatosMaestrosEntidadesObraProyectosIndexRoute =
  AuthenticatedDatosMaestrosEntidadesObraProyectosIndexRouteImport.update({
    id: '/entidades-obra/proyectos/',
    path: '/entidades-obra/proyectos/',
    getParentRoute: () => AuthenticatedDatosMaestrosRoute,
  } as any)
const AuthenticatedDatosMaestrosEntidadesObraProyectosIdRoute =
  AuthenticatedDatosMaestrosEntidadesObraProyectosIdRouteImport.update({
    id: '/entidades-obra/proyectos/$id',
    path: '/entidades-obra/proyectos/$id',
    getParentRoute: () => AuthenticatedDatosMaestrosRoute,
  } as any)
const AuthenticatedDigitalAppsActasReunionIndexRoute =
  AuthenticatedDigitalAppsActasReunionIndexRouteImport.update({
    id: '/actas-reunion/',
    path: '/actas-reunion/',
    getParentRoute: () => AuthenticatedDigitalAppsRoute,
  } as any)
const AuthenticatedDigitalAppsActasReunionNewRoute =
  AuthenticatedDigitalAppsActasReunionNewRouteImport.update({
    id: '/actas-reunion/new',
    path: '/actas-reunion/new',
    getParentRoute: () => AuthenticatedDigitalAppsRoute,
  } as any)
const AuthenticatedDigitalAppsActasReunionIdIndexRoute =
  AuthenticatedDigitalAppsActasReunionIdIndexRouteImport.update({
    id: '/actas-reunion/$id/',
    path: '/actas-reunion/$id/',
    getParentRoute: () => AuthenticatedDigitalAppsRoute,
  } as any)
const AuthenticatedDigitalAppsActasReunionIdEditRoute =
  AuthenticatedDigitalAppsActasReunionIdEditRouteImport.update({
    id: '/actas-reunion/$id/edit',
    path: '/actas-reunion/$id/edit',
    getParentRoute: () => AuthenticatedDigitalAppsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/datos-maestros': typeof AuthenticatedDatosMaestrosRouteWithChildren
  '/digital/agentes': typeof AuthenticatedDigitalAgentesRoute
  '/digital/apps': typeof AuthenticatedDigitalAppsRouteWithChildren
  '/digital/inicio': typeof AuthenticatedDigitalInicioRoute
  '/hub/inicio': typeof AuthenticatedHubInicioRoute
  '/hub/modulos': typeof AuthenticatedHubModulosRoute
  '/hub/proyectos': typeof AuthenticatedHubProyectosRoute
  '/datos-maestros/': typeof AuthenticatedDatosMaestrosIndexRoute
  '/datos-maestros/accesos-equipo/catalogos': typeof AuthenticatedDatosMaestrosAccesosEquipoCatalogosRoute
  '/datos-maestros/accesos-equipo/personal-externo': typeof AuthenticatedDatosMaestrosAccesosEquipoPersonalExternoRoute
  '/datos-maestros/accesos-equipo/personal-propio': typeof AuthenticatedDatosMaestrosAccesosEquipoPersonalPropioRoute
  '/datos-maestros/accesos-equipo/usuarios': typeof AuthenticatedDatosMaestrosAccesosEquipoUsuariosRoute
  '/datos-maestros/entidades-obra/direccion-facultativa': typeof AuthenticatedDatosMaestrosEntidadesObraDireccionFacultativaRoute
  '/proyecto/$id/inicio': typeof AuthenticatedProyectoIdInicioRoute
  '/proyecto/$id/modulos': typeof AuthenticatedProyectoIdModulosRoute
  '/digital/apps/': typeof AuthenticatedDigitalAppsIndexRoute
  '/datos-maestros/entidades-obra/propiedad/$id': typeof AuthenticatedDatosMaestrosEntidadesObraPropiedadIdRoute
  '/datos-maestros/entidades-obra/proyectos/$id': typeof AuthenticatedDatosMaestrosEntidadesObraProyectosIdRoute
  '/digital/apps/actas-reunion/new': typeof AuthenticatedDigitalAppsActasReunionNewRoute
  '/datos-maestros/entidades-obra/propiedad/': typeof AuthenticatedDatosMaestrosEntidadesObraPropiedadIndexRoute
  '/datos-maestros/entidades-obra/proyectos/': typeof AuthenticatedDatosMaestrosEntidadesObraProyectosIndexRoute
  '/digital/apps/actas-reunion/': typeof AuthenticatedDigitalAppsActasReunionIndexRoute
  '/digital/apps/actas-reunion/$id/edit': typeof AuthenticatedDigitalAppsActasReunionIdEditRoute
  '/digital/apps/actas-reunion/$id/': typeof AuthenticatedDigitalAppsActasReunionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/digital/agentes': typeof AuthenticatedDigitalAgentesRoute
  '/digital/inicio': typeof AuthenticatedDigitalInicioRoute
  '/hub/inicio': typeof AuthenticatedHubInicioRoute
  '/hub/modulos': typeof AuthenticatedHubModulosRoute
  '/hub/proyectos': typeof AuthenticatedHubProyectosRoute
  '/datos-maestros': typeof AuthenticatedDatosMaestrosIndexRoute
  '/datos-maestros/accesos-equipo/catalogos': typeof AuthenticatedDatosMaestrosAccesosEquipoCatalogosRoute
  '/datos-maestros/accesos-equipo/personal-externo': typeof AuthenticatedDatosMaestrosAccesosEquipoPersonalExternoRoute
  '/datos-maestros/accesos-equipo/personal-propio': typeof AuthenticatedDatosMaestrosAccesosEquipoPersonalPropioRoute
  '/datos-maestros/accesos-equipo/usuarios': typeof AuthenticatedDatosMaestrosAccesosEquipoUsuariosRoute
  '/datos-maestros/entidades-obra/direccion-facultativa': typeof AuthenticatedDatosMaestrosEntidadesObraDireccionFacultativaRoute
  '/proyecto/$id/inicio': typeof AuthenticatedProyectoIdInicioRoute
  '/proyecto/$id/modulos': typeof AuthenticatedProyectoIdModulosRoute
  '/digital/apps': typeof AuthenticatedDigitalAppsIndexRoute
  '/datos-maestros/entidades-obra/propiedad/$id': typeof AuthenticatedDatosMaestrosEntidadesObraPropiedadIdRoute
  '/datos-maestros/entidades-obra/proyectos/$id': typeof AuthenticatedDatosMaestrosEntidadesObraProyectosIdRoute
  '/digital/apps/actas-reunion/new': typeof AuthenticatedDigitalAppsActasReunionNewRoute
  '/datos-maestros/entidades-obra/propiedad': typeof AuthenticatedDatosMaestrosEntidadesObraPropiedadIndexRoute
  '/datos-maestros/entidades-obra/proyectos': typeof AuthenticatedDatosMaestrosEntidadesObraProyectosIndexRoute
  '/digital/apps/actas-reunion': typeof AuthenticatedDigitalAppsActasReunionIndexRoute
  '/digital/apps/actas-reunion/$id/edit': typeof AuthenticatedDigitalAppsActasReunionIdEditRoute
  '/digital/apps/actas-reunion/$id': typeof AuthenticatedDigitalAppsActasReunionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/datos-maestros': typeof AuthenticatedDatosMaestrosRouteWithChildren
  '/_authenticated/digital/agentes': typeof AuthenticatedDigitalAgentesRoute
  '/_authenticated/digital/apps': typeof AuthenticatedDigitalAppsRouteWithChildren
  '/_authenticated/digital/inicio': typeof AuthenticatedDigitalInicioRoute
  '/_authenticated/hub/inicio': typeof AuthenticatedHubInicioRoute
  '/_authenticated/hub/modulos': typeof AuthenticatedHubModulosRoute
  '/_authenticated/hub/proyectos': typeof AuthenticatedHubProyectosRoute
  '/_authenticated/datos-maestros/': typeof AuthenticatedDatosMaestrosIndexRoute
  '/_authenticated/datos-maestros/accesos-equipo/catalogos': typeof AuthenticatedDatosMaestrosAccesosEquipoCatalogosRoute
  '/_authenticated/datos-maestros/accesos-equipo/personal-externo': typeof AuthenticatedDatosMaestrosAccesosEquipoPersonalExternoRoute
  '/_authenticated/datos-maestros/accesos-equipo/personal-propio': typeof AuthenticatedDatosMaestrosAccesosEquipoPersonalPropioRoute
  '/_authenticated/datos-maestros/accesos-equipo/usuarios': typeof AuthenticatedDatosMaestrosAccesosEquipoUsuariosRoute
  '/_authenticated/datos-maestros/entidades-obra/direccion-facultativa': typeof AuthenticatedDatosMaestrosEntidadesObraDireccionFacultativaRoute
  '/_authenticated/proyecto/$id/inicio': typeof AuthenticatedProyectoIdInicioRoute
  '/_authenticated/proyecto/$id/modulos': typeof AuthenticatedProyectoIdModulosRoute
  '/_authenticated/digital/apps/': typeof AuthenticatedDigitalAppsIndexRoute
  '/_authenticated/datos-maestros/entidades-obra/propiedad/$id': typeof AuthenticatedDatosMaestrosEntidadesObraPropiedadIdRoute
  '/_authenticated/datos-maestros/entidades-obra/proyectos/$id': typeof AuthenticatedDatosMaestrosEntidadesObraProyectosIdRoute
  '/_authenticated/digital/apps/actas-reunion/new': typeof AuthenticatedDigitalAppsActasReunionNewRoute
  '/_authenticated/datos-maestros/entidades-obra/propiedad/': typeof AuthenticatedDatosMaestrosEntidadesObraPropiedadIndexRoute
  '/_authenticated/datos-maestros/entidades-obra/proyectos/': typeof AuthenticatedDatosMaestrosEntidadesObraProyectosIndexRoute
  '/_authenticated/digital/apps/actas-reunion/': typeof AuthenticatedDigitalAppsActasReunionIndexRoute
  '/_authenticated/digital/apps/actas-reunion/$id/edit': typeof AuthenticatedDigitalAppsActasReunionIdEditRoute
  '/_authenticated/digital/apps/actas-reunion/$id/': typeof AuthenticatedDigitalAppsActasReunionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configuracion'
    | '/datos-maestros'
    | '/digital/agentes'
    | '/digital/apps'
    | '/digital/inicio'
    | '/hub/inicio'
    | '/hub/modulos'
    | '/hub/proyectos'
    | '/datos-maestros/'
    | '/datos-maestros/accesos-equipo/catalogos'
    | '/datos-maestros/accesos-equipo/personal-externo'
    | '/datos-maestros/accesos-equipo/personal-propio'
    | '/datos-maestros/accesos-equipo/usuarios'
    | '/datos-maestros/entidades-obra/direccion-facultativa'
    | '/proyecto/$id/inicio'
    | '/proyecto/$id/modulos'
    | '/digital/apps/'
    | '/datos-maestros/entidades-obra/propiedad/$id'
    | '/datos-maestros/entidades-obra/proyectos/$id'
    | '/digital/apps/actas-reunion/new'
    | '/datos-maestros/entidades-obra/propiedad/'
    | '/datos-maestros/entidades-obra/proyectos/'
    | '/digital/apps/actas-reunion/'
    | '/digital/apps/actas-reunion/$id/edit'
    | '/digital/apps/actas-reunion/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/configuracion'
    | '/digital/agentes'
    | '/digital/inicio'
    | '/hub/inicio'
    | '/hub/modulos'
    | '/hub/proyectos'
    | '/datos-maestros'
    | '/datos-maestros/accesos-equipo/catalogos'
    | '/datos-maestros/accesos-equipo/personal-externo'
    | '/datos-maestros/accesos-equipo/personal-propio'
    | '/datos-maestros/accesos-equipo/usuarios'
    | '/datos-maestros/entidades-obra/direccion-facultativa'
    | '/proyecto/$id/inicio'
    | '/proyecto/$id/modulos'
    | '/digital/apps'
    | '/datos-maestros/entidades-obra/propiedad/$id'
    | '/datos-maestros/entidades-obra/proyectos/$id'
    | '/digital/apps/actas-reunion/new'
    | '/datos-maestros/entidades-obra/propiedad'
    | '/datos-maestros/entidades-obra/proyectos'
    | '/digital/apps/actas-reunion'
    | '/digital/apps/actas-reunion/$id/edit'
    | '/digital/apps/actas-reunion/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/configuracion'
    | '/_authenticated/datos-maestros'
    | '/_authenticated/digital/agentes'
    | '/_authenticated/digital/apps'
    | '/_authenticated/digital/inicio'
    | '/_authenticated/hub/inicio'
    | '/_authenticated/hub/modulos'
    | '/_authenticated/hub/proyectos'
    | '/_authenticated/datos-maestros/'
    | '/_authenticated/datos-maestros/accesos-equipo/catalogos'
    | '/_authenticated/datos-maestros/accesos-equipo/personal-externo'
    | '/_authenticated/datos-maestros/accesos-equipo/personal-propio'
    | '/_authenticated/datos-maestros/accesos-equipo/usuarios'
    | '/_authenticated/datos-maestros/entidades-obra/direccion-facultativa'
    | '/_authenticated/proyecto/$id/inicio'
    | '/_authenticated/proyecto/$id/modulos'
    | '/_authenticated/digital/apps/'
    | '/_authenticated/datos-maestros/entidades-obra/propiedad/$id'
    | '/_authenticated/datos-maestros/entidades-obra/proyectos/$id'
    | '/_authenticated/digital/apps/actas-reunion/new'
    | '/_authenticated/datos-maestros/entidades-obra/propiedad/'
    | '/_authenticated/datos-maestros/entidades-obra/proyectos/'
    | '/_authenticated/digital/apps/actas-reunion/'
    | '/_authenticated/digital/apps/actas-reunion/$id/edit'
    | '/_authenticated/digital/apps/actas-reunion/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datos-maestros': {
      id: '/_authenticated/datos-maestros'
      path: '/datos-maestros'
      fullPath: '/datos-maestros'
      preLoaderRoute: typeof AuthenticatedDatosMaestrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datos-maestros/': {
      id: '/_authenticated/datos-maestros/'
      path: '/'
      fullPath: '/datos-maestros/'
      preLoaderRoute: typeof AuthenticatedDatosMaestrosIndexRouteImport
      parentRoute: typeof AuthenticatedDatosMaestrosRoute
    }
    '/_authenticated/digital/agentes': {
      id: '/_authenticated/digital/agentes'
      path: '/digital/agentes'
      fullPath: '/digital/agentes'
      preLoaderRoute: typeof AuthenticatedDigitalAgentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/digital/apps': {
      id: '/_authenticated/digital/apps'
      path: '/digital/apps'
      fullPath: '/digital/apps'
      preLoaderRoute: typeof AuthenticatedDigitalAppsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/digital/inicio': {
      id: '/_authenticated/digital/inicio'
      path: '/digital/inicio'
      fullPath: '/digital/inicio'
      preLoaderRoute: typeof AuthenticatedDigitalInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hub/inicio': {
      id: '/_authenticated/hub/inicio'
      path: '/hub/inicio'
      fullPath: '/hub/inicio'
      preLoaderRoute: typeof AuthenticatedHubInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hub/modulos': {
      id: '/_authenticated/hub/modulos'
      path: '/hub/modulos'
      fullPath: '/hub/modulos'
      preLoaderRoute: typeof AuthenticatedHubModulosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hub/proyectos': {
      id: '/_authenticated/hub/proyectos'
      path: '/hub/proyectos'
      fullPath: '/hub/proyectos'
      preLoaderRoute: typeof AuthenticatedHubProyectosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datos-maestros/accesos-equipo/catalogos': {
      id: '/_authenticated/datos-maestros/accesos-equipo/catalogos'
      path: '/accesos-equipo/catalogos'
      fullPath: '/datos-maestros/accesos-equipo/catalogos'
      preLoaderRoute: typeof AuthenticatedDatosMaestrosAccesosEquipoCatalogosRouteImport
      parentRoute: typeof AuthenticatedDatosMaestrosRoute
    }
    '/_authenticated/datos-maestros/accesos-equipo/personal-externo': {
      id: '/_authenticated/datos-maestros/accesos-equipo/personal-externo'
      path: '/accesos-equipo/personal-externo'
      fullPath: '/datos-maestros/accesos-equipo/personal-externo'
      preLoaderRoute: typeof AuthenticatedDatosMaestrosAccesosEquipoPersonalExternoRouteImport
      parentRoute: typeof AuthenticatedDatosMaestrosRoute
    }
    '/_authenticated/datos-maestros/accesos-equipo/personal-propio': {
      id: '/_authenticated/datos-maestros/accesos-equipo/personal-propio'
      path: '/accesos-equipo/personal-propio'
      fullPath: '/datos-maestros/accesos-equipo/personal-propio'
      preLoaderRoute: typeof AuthenticatedDatosMaestrosAccesosEquipoPersonalPropioRouteImport
      parentRoute: typeof AuthenticatedDatosMaestrosRoute
    }
    '/_authenticated/datos-maestros/accesos-equipo/usuarios': {
      id: '/_authenticated/datos-maestros/accesos-equipo/usuarios'
      path: '/accesos-equipo/usuarios'
      fullPath: '/datos-maestros/accesos-equipo/usuarios'
      preLoaderRoute: typeof AuthenticatedDatosMaestrosAccesosEquipoUsuariosRouteImport
      parentRoute: typeof AuthenticatedDatosMaestrosRoute
    }
    '/_authenticated/datos-maestros/entidades-obra/direccion-facultativa': {
      id: '/_authenticated/datos-maestros/entidades-obra/direccion-facultativa'
      path: '/entidades-obra/direccion-facultativa'
      fullPath: '/datos-maestros/entidades-obra/direccion-facultativa'
      preLoaderRoute: typeof AuthenticatedDatosMaestrosEntidadesObraDireccionFacultativaRouteImport
      parentRoute: typeof AuthenticatedDatosMaestrosRoute
    }
    '/_authenticated/digital/apps/': {
      id: '/_authenticated/digital/apps/'
      path: '/'
      fullPath: '/digital/apps/'
      preLoaderRoute: typeof AuthenticatedDigitalAppsIndexRouteImport
      parentRoute: typeof AuthenticatedDigitalAppsRoute
    }
    '/_authenticated/proyecto/$id/inicio': {
      id: '/_authenticated/proyecto/$id/inicio'
      path: '/proyecto/$id/inicio'
      fullPath: '/proyecto/$id/inicio'
      preLoaderRoute: typeof AuthenticatedProyectoIdInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proyecto/$id/modulos': {
      id: '/_authenticated/proyecto/$id/modulos'
      path: '/proyecto/$id/modulos'
      fullPath: '/proyecto/$id/modulos'
      preLoaderRoute: typeof AuthenticatedProyectoIdModulosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datos-maestros/entidades-obra/propiedad/': {
      id: '/_authenticated/datos-maestros/entidades-obra/propiedad/'
      path: '/entidades-obra/propiedad'
      fullPath: '/datos-maestros/entidades-obra/propiedad/'
      preLoaderRoute: typeof AuthenticatedDatosMaestrosEntidadesObraPropiedadIndexRouteImport
      parentRoute: typeof AuthenticatedDatosMaestrosRoute
    }
    '/_authenticated/datos-maestros/entidades-obra/propiedad/$id': {
      id: '/_authenticated/datos-maestros/entidades-obra/propiedad/$id'
      path: '/entidades-obra/propiedad/$id'
      fullPath: '/datos-maestros/entidades-obra/propiedad/$id'
      preLoaderRoute: typeof AuthenticatedDatosMaestrosEntidadesObraPropiedadIdRouteImport
      parentRoute: typeof AuthenticatedDatosMaestrosRoute
    }
    '/_authenticated/datos-maestros/entidades-obra/proyectos/': {
      id: '/_authenticated/datos-maestros/entidades-obra/proyectos/'
      path: '/entidades-obra/proyectos'
      fullPath: '/datos-maestros/entidades-obra/proyectos/'
      preLoaderRoute: typeof AuthenticatedDatosMaestrosEntidadesObraProyectosIndexRouteImport
      parentRoute: typeof AuthenticatedDatosMaestrosRoute
    }
    '/_authenticated/datos-maestros/entidades-obra/proyectos/$id': {
      id: '/_authenticated/datos-maestros/entidades-obra/proyectos/$id'
      path: '/entidades-obra/proyectos/$id'
      fullPath: '/datos-maestros/entidades-obra/proyectos/$id'
      preLoaderRoute: typeof AuthenticatedDatosMaestrosEntidadesObraProyectosIdRouteImport
      parentRoute: typeof AuthenticatedDatosMaestrosRoute
    }
    '/_authenticated/digital/apps/actas-reunion/': {
      id: '/_authenticated/digital/apps/actas-reunion/'
      path: '/actas-reunion'
      fullPath: '/digital/apps/actas-reunion/'
      preLoaderRoute: typeof AuthenticatedDigitalAppsActasReunionIndexRouteImport
      parentRoute: typeof AuthenticatedDigitalAppsRoute
    }
    '/_authenticated/digital/apps/actas-reunion/new': {
      id: '/_authenticated/digital/apps/actas-reunion/new'
      path: '/actas-reunion/new'
      fullPath: '/digital/apps/actas-reunion/new'
      preLoaderRoute: typeof AuthenticatedDigitalAppsActasReunionNewRouteImport
      parentRoute: typeof AuthenticatedDigitalAppsRoute
    }
    '/_authenticated/digital/apps/actas-reunion/$id/': {
      id: '/_authenticated/digital/apps/actas-reunion/$id/'
      path: '/actas-reunion/$id'
      fullPath: '/digital/apps/actas-reunion/$id/'
      preLoaderRoute: typeof AuthenticatedDigitalAppsActasReunionIdIndexRouteImport
      parentRoute: typeof AuthenticatedDigitalAppsRoute
    }
    '/_authenticated/digital/apps/actas-reunion/$id/edit': {
      id: '/_authenticated/digital/apps/actas-reunion/$id/edit'
      path: '/actas-reunion/$id/edit'
      fullPath: '/digital/apps/actas-reunion/$id/edit'
      preLoaderRoute: typeof AuthenticatedDigitalAppsActasReunionIdEditRouteImport
      parentRoute: typeof AuthenticatedDigitalAppsRoute
    }
  }
}

interface AuthenticatedDatosMaestrosRouteChildren {
  AuthenticatedDatosMaestrosIndexRoute: typeof AuthenticatedDatosMaestrosIndexRoute
  AuthenticatedDatosMaestrosAccesosEquipoCatalogosRoute: typeof AuthenticatedDatosMaestrosAccesosEquipoCatalogosRoute
  AuthenticatedDatosMaestrosAccesosEquipoPersonalExternoRoute: typeof AuthenticatedDatosMaestrosAccesosEquipoPersonalExternoRoute
  AuthenticatedDatosMaestrosAccesosEquipoPersonalPropioRoute: typeof AuthenticatedDatosMaestrosAccesosEquipoPersonalPropioRoute
  AuthenticatedDatosMaestrosAccesosEquipoUsuariosRoute: typeof AuthenticatedDatosMaestrosAccesosEquipoUsuariosRoute
  AuthenticatedDatosMaestrosEntidadesObraDireccionFacultativaRoute: typeof AuthenticatedDatosMaestrosEntidadesObraDireccionFacultativaRoute
  AuthenticatedDatosMaestrosEntidadesObraPropiedadIdRoute: typeof AuthenticatedDatosMaestrosEntidadesObraPropiedadIdRoute
  AuthenticatedDatosMaestrosEntidadesObraProyectosIdRoute: typeof AuthenticatedDatosMaestrosEntidadesObraProyectosIdRoute
  AuthenticatedDatosMaestrosEntidadesObraPropiedadIndexRoute: typeof AuthenticatedDatosMaestrosEntidadesObraPropiedadIndexRoute
  AuthenticatedDatosMaestrosEntidadesObraProyectosIndexRoute: typeof AuthenticatedDatosMaestrosEntidadesObraProyectosIndexRoute
}

const AuthenticatedDatosMaestrosRouteChildren: AuthenticatedDatosMaestrosRouteChildren =
  {
    AuthenticatedDatosMaestrosIndexRoute: AuthenticatedDatosMaestrosIndexRoute,
    AuthenticatedDatosMaestrosAccesosEquipoCatalogosRoute:
      AuthenticatedDatosMaestrosAccesosEquipoCatalogosRoute,
    AuthenticatedDatosMaestrosAccesosEquipoPersonalExternoRoute:
      AuthenticatedDatosMaestrosAccesosEquipoPersonalExternoRoute,
    AuthenticatedDatosMaestrosAccesosEquipoPersonalPropioRoute:
      AuthenticatedDatosMaestrosAccesosEquipoPersonalPropioRoute,
    AuthenticatedDatosMaestrosAccesosEquipoUsuariosRoute:
      AuthenticatedDatosMaestrosAccesosEquipoUsuariosRoute,
    AuthenticatedDatosMaestrosEntidadesObraDireccionFacultativaRoute:
      AuthenticatedDatosMaestrosEntidadesObraDireccionFacultativaRoute,
    AuthenticatedDatosMaestrosEntidadesObraPropiedadIdRoute:
      AuthenticatedDatosMaestrosEntidadesObraPropiedadIdRoute,
    AuthenticatedDatosMaestrosEntidadesObraProyectosIdRoute:
      AuthenticatedDatosMaestrosEntidadesObraProyectosIdRoute,
    AuthenticatedDatosMaestrosEntidadesObraPropiedadIndexRoute:
      AuthenticatedDatosMaestrosEntidadesObraPropiedadIndexRoute,
    AuthenticatedDatosMaestrosEntidadesObraProyectosIndexRoute:
      AuthenticatedDatosMaestrosEntidadesObraProyectosIndexRoute,
  }

const AuthenticatedDatosMaestrosRouteWithChildren =
  AuthenticatedDatosMaestrosRoute._addFileChildren(
    AuthenticatedDatosMaestrosRouteChildren,
  )

interface AuthenticatedDigitalAppsRouteChildren {
  AuthenticatedDigitalAppsIndexRoute: typeof AuthenticatedDigitalAppsIndexRoute
  AuthenticatedDigitalAppsActasReunionNewRoute: typeof AuthenticatedDigitalAppsActasReunionNewRoute
  AuthenticatedDigitalAppsActasReunionIndexRoute: typeof AuthenticatedDigitalAppsActasReunionIndexRoute
  AuthenticatedDigitalAppsActasReunionIdEditRoute: typeof AuthenticatedDigitalAppsActasReunionIdEditRoute
  AuthenticatedDigitalAppsActasReunionIdIndexRoute: typeof AuthenticatedDigitalAppsActasReunionIdIndexRoute
}

const AuthenticatedDigitalAppsRouteChildren: AuthenticatedDigitalAppsRouteChildren =
  {
    AuthenticatedDigitalAppsIndexRoute: AuthenticatedDigitalAppsIndexRoute,
    AuthenticatedDigitalAppsActasReunionNewRoute:
      AuthenticatedDigitalAppsActasReunionNewRoute,
    AuthenticatedDigitalAppsActasReunionIndexRoute:
      AuthenticatedDigitalAppsActasReunionIndexRoute,
    AuthenticatedDigitalAppsActasReunionIdEditRoute:
      AuthenticatedDigitalAppsActasReunionIdEditRoute,
    AuthenticatedDigitalAppsActasReunionIdIndexRoute:
      AuthenticatedDigitalAppsActasReunionIdIndexRoute,
  }

const AuthenticatedDigitalAppsRouteWithChildren =
  AuthenticatedDigitalAppsRoute._addFileChildren(
    AuthenticatedDigitalAppsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedDatosMaestrosRoute: typeof AuthenticatedDatosMaestrosRouteWithChildren
  AuthenticatedDigitalAgentesRoute: typeof AuthenticatedDigitalAgentesRoute
  AuthenticatedDigitalAppsRoute: typeof AuthenticatedDigitalAppsRouteWithChildren
  AuthenticatedDigitalInicioRoute: typeof AuthenticatedDigitalInicioRoute
  AuthenticatedHubInicioRoute: typeof AuthenticatedHubInicioRoute
  AuthenticatedHubModulosRoute: typeof AuthenticatedHubModulosRoute
  AuthenticatedHubProyectosRoute: typeof AuthenticatedHubProyectosRoute
  AuthenticatedProyectoIdInicioRoute: typeof AuthenticatedProyectoIdInicioRoute
  AuthenticatedProyectoIdModulosRoute: typeof AuthenticatedProyectoIdModulosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedDatosMaestrosRoute: AuthenticatedDatosMaestrosRouteWithChildren,
  AuthenticatedDigitalAgentesRoute: AuthenticatedDigitalAgentesRoute,
  AuthenticatedDigitalAppsRoute: AuthenticatedDigitalAppsRouteWithChildren,
  AuthenticatedDigitalInicioRoute: AuthenticatedDigitalInicioRoute,
  AuthenticatedHubInicioRoute: AuthenticatedHubInicioRoute,
  AuthenticatedHubModulosRoute: AuthenticatedHubModulosRoute,
  AuthenticatedHubProyectosRoute: AuthenticatedHubProyectosRoute,
  AuthenticatedProyectoIdInicioRoute: AuthenticatedProyectoIdInicioRoute,
  AuthenticatedProyectoIdModulosRoute: AuthenticatedProyectoIdModulosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
